# Generated by Django 5.1.7 on 2025-07-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('pending', 'في الانتظار'), ('sold', 'تم البيع'), ('expired', 'منتهي الصلاحية'), ('rejected', 'مرفوض')], default='active', max_length=20),
        ),
    ]
