# Generated by Django 5.1.7 on 2025-07-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('items', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='items.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
